import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiProxyRouter from "./ai-proxy";
import companiesRouter from "./companies";
import fileManagerRouter from "./fileManager";
import apaleoRouter from "./apaleo";
import agentsRouter from "./agents";
import mcpProxyRouter from "./mcp-proxy";
import mcpGovernanceRouter from "./mcp-governance";
import seedRouter from "./seed";
import a2aRouter from "./a2a";
import hitlRouter from "./hitl";
import onboardingRollbackRouter from "../onboarding/onboardingRollback";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import euAiActRouter from "./euAiAct";
import gdprRouter from "./gdpr";
import ucpRouter from "./ucp";
import billingRouter from "./billing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(aiProxyRouter);
router.use(companiesRouter);
router.use(fileManagerRouter);
router.use(apaleoRouter);
router.use(agentsRouter);
router.use(mcpProxyRouter);
router.use(mcpGovernanceRouter);
router.use(seedRouter);
router.use(a2aRouter);
router.use(hitlRouter);
router.use(onboardingRollbackRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(euAiActRouter);
router.use(gdprRouter);
router.use(ucpRouter);
router.use(billingRouter);

export default router;
