/**
 * stayAgentCard.ts — Stay Agent's A2A card, built to the LIVE suite shape (matching
 * hitl.getvda.ai), from the single skill definition in stayAgentSkills.ts.
 *
 * It describes what Stay Agent IS TODAY, honestly: a bespoke hospitality monolith running
 * on the Apaleo sandbox, with no identity of its own. It is deliberately NOT normalised to
 * the future adapter state — the gap between this card and the governance model is exactly
 * what Onboarding's admission is meant to surface.
 *
 * NOT signed. Stay Agent has no key/DID/Witness account; agentCardSignature is intentionally
 * absent, and `witnessAccountId` names the SHARED account it currently borrows.
 */
import { cardSkills } from "./stayAgentSkills.js";

const GIT_SHA = process.env.STAY_GIT_SHA || "89ddedc319efa7b8569a5b45ae44781e313540af"; // deployed Vercel branch @ audit
const SHARED_WITNESS_ACCOUNT = process.env.WITNESS_EXPECTED_ACCOUNT || "acct_01KX3TQ8Z0ME1455RW16JC4ENQ";

export function buildStayAgentCard(now: string) {
  return {
    protocolVersion: "0.3.0",
    name: "citizenM Stay Agent",
    description:
      "Governs a hotel guest's on-property journey (check-in, in-stay, check-out) at citizenM by proposing actions on Apaleo exceptions and routing the ones beyond its authority to a human. A bespoke build, not yet a normalised VDA deployment: it decides its own authority, runs its own human queue, executes its own writes, and seals under a borrowed identity. Running against the Apaleo SANDBOX only.",
    url: "https://stay-agent-mikerawsonnzs-projects.vercel.app",
    preferredTransport: "JSONRPC",
    version: "0.0.0-predeployment",
    gitSha: GIT_SHA,

    provider: { organization: "citizenM Hotels", url: "https://citizenm.com" },

    capabilities: { streaming: false, pushNotifications: false, stateTransitionHistory: true },
    defaultInputModes: ["application/json", "text/plain"],
    defaultOutputModes: ["application/json"],

    skills: cardSkills(),

    // Exactly what Stay touches in Apaleo, read vs write. Sandbox only today.
    apaleoScopes: {
      environment: "sandbox",
      read: [
        "GET /booking/v1/reservations/{id} — the reservation a decision is about",
        "GET /finance/v1/folios/{id} and /finance/v1/folios?reservationIds=… — folio status, balance, line items, disputes",
        "GET /inventory/v1/properties — property roster",
      ],
      write: [
        "CheckIn — reservation check-in",
        "CheckOut — reservation check-out",
        "CreateFolioCharge — post a charge to a folio (moves real money in production; sandbox only today)",
        "AmendReservation — shorten/modify a reservation (e.g. release nights on early check-out)",
      ],
      note: "Writes execute INLINE on a governed PASS (lib/stayExecutor.ts) — this agent both decides and writes. Full reservation/folio objects (guest PII included) are read and reach the LLM prompt unminimised; see the no_pii_minimisation_despite_claim caveat.",
    },

    // What Stay Agent genuinely delegates. This list is SHORT on purpose — today Stay owns
    // almost everything the framework would own for it, and that shortness is the finding.
    doesNotOwn: [
      {
        concern: "the tamper-evident ledger and external anchoring",
        owner: "VDA Witness",
        note: "Stay seals TO Witness; it does not run the hash chain, custodial sealing, or the hourly Rekor/TSA anchoring. But it seals under a shared account, not one it owns — see the no_own_identity caveat.",
      },
      {
        concern: "the EU AI Act article/risk logic",
        owner: "C2MD",
        note: "The Article-by-Article assessment is generated by C2MD via the Witness suite key; Stay orchestrates and renders it. The Article 12 record-keeping report is generated by Witness from the trail.",
      },
    ],

    // The honest gaps. Each is something the framework now does generically that Stay still
    // does bespoke, or a claim its surface makes that its implementation does not support.
    caveats: [
      {
        id: "decides_own_authority_hardcoded_bands",
        statement: "Stay computes its own escalation authority in code, against a hardcoded band ladder — not a signed ACP bundle evaluated by ACP's SDK.",
        detail: "The ladder ambassador -> mod -> compliance_officer is a code constant (routes/stay.ts NEXT_BAND); the decision engine calls its ceiling rules against those literal band names (stayDecisionEngine.ts). Authority here is self-asserted, not framework-enforced. This is the single biggest divergence from the governance model.",
      },
      {
        id: "runs_own_hitl",
        statement: "Stay hosts its own human-in-the-loop queue instead of raising items to hitl.getvda.ai.",
        detail: "/stay/hitl/* (pending + respond) is a second implementation of the concept the live HITL service already provides. The two would need to converge for Stay to be a deployment on the substrate rather than a fork of it.",
      },
      {
        id: "executes_domain_writes_inline",
        statement: "Stay both decides AND executes the Apaleo write on a governed PASS.",
        detail: "CheckIn / CheckOut / CreateFolioCharge / AmendReservation are performed inline by the decision path (lib/stayExecutor.ts). The framework model is record-then-the-deployment-executes; Stay fuses the two.",
      },
      {
        id: "no_own_identity",
        statement: "Stay has no keys, no DID, and no Witness account of its own. It cannot sign this card.",
        detail: "It runs inside vda-api and seals under a shared Witness account (" + SHARED_WITNESS_ACCOUNT + "). A legacy code path (lib/vdaWitness.ts) falls back to a personal email (mikerawsonnz@gmail.com) if WITNESS_KEY_EMAIL is unset. Custody is therefore custodial-under-a-borrowed-account: an enforcer cannot prove THIS agent signed a decision. Provisioning an own account is a prerequisite to signing (step 2).",
      },
      {
        id: "actor_asserted_and_endpoints_unauthenticated",
        statement: "Human resolutions record who the caller SAYS decided; the human is not authenticated and the endpoints have no auth.",
        detail: "resolve_decision writes decided_by from the request body (defaulting to 'Dashboard User'); there is no auth middleware on the Stay routes. Anyone who can reach the service can resolve a governance decision under a name of their choosing.",
      },
      {
        id: "no_pii_minimisation_despite_claim",
        statement: "Stay fetches whole Apaleo reservation/folio objects — including guest PII — and serialises them into the LLM prompt and the human-queue payload. No PII-minimisation layer exists, despite the GDPR report asserting one.",
        detail: "fetchApaleoSnapshot returns full objects; they reach a third-party LLM verbatim and the HITL payload. Only the Witness SEAL is PII-safe (hash + descriptor). The GDPR report's Article 25 'Presidio scrubbing' claim is not backed by code (see the vda-api findings). Mitigated only by sandbox data.",
      },
    ],

    custody: {
      model: "custodial-under-borrowed-account",
      recordSigningKey: null,
      statement:
        "Stay Agent holds no signing key. Decisions are sealed under vda-api's shared Witness identity, not a key Stay controls. An enforcer can see that Witness recorded a decision under the shared account; it cannot prove that Stay Agent, specifically, signed it. Contrast the suite standard (customer-managed, own record-signing key).",
      issuerVerification: "none — no did:web for Stay Agent yet",
    },

    // A self-report of the real state — NOT a live-probe of a genuine, admitted service.
    status: {
      checkedAt: now,
      environment: "apaleo_sandbox",
      production: false,
      carries_real_guests: false,
      carries_real_money: false,
      admitted: false,
      admission_note: "No Onboarding credential. This card is being produced AS the admission entry ticket; it is not yet signed or registered.",
      identity: "borrowed — seals under shared account " + SHARED_WITNESS_ACCOUNT,
      note: "These are honest self-declared facts about a pre-deployment demo, not the output of live readiness probes against an admitted service.",
    },

    // Contracts Stay actually honours today. It does NOT yet implement suite auth-via-whoami.
    contracts: [],

    witnessAccountId: SHARED_WITNESS_ACCOUNT, // borrowed, not owned — see custody + no_own_identity

    // agentCardSignature: intentionally ABSENT. Stay has no key to sign with; signing is step 2.
  };
}
