/**
 * stayAgentCard.ts — Stay Agent's A2A card, built to the LIVE suite shape (matching
 * hitl.getvda.ai), from the single skill definition in stayAgentSkills.ts.
 *
 * It describes what Stay Agent IS TODAY, honestly: a bespoke hospitality monolith running
 * on the Apaleo sandbox. It is deliberately NOT normalised to the future adapter state —
 * the gap between this card and the governance model is exactly what Onboarding's admission
 * is meant to surface.
 *
 * SIGNED, as of the did:web genesis. Stay Agent now controls one key — the `#key-1` that
 * signs this card and answers DID-auth challenges — so `agentCardSignature` is real and
 * `did` is resolvable. Read the scope of that narrowly: it does NOT mean Stay Agent owns
 * its seal custody. `witnessAccountId` still names a SHARED account it borrows, and it
 * still holds no record-signing key, so an enforcer can verify that THIS agent published
 * THIS card and cannot verify that THIS agent sealed a given decision. Those are two
 * different keys and only the first one exists; see `custody` and the caveats.
 */
import { cardSkills } from "./stayAgentSkills.js";

const GIT_SHA = process.env.STAY_GIT_SHA || "89ddedc319efa7b8569a5b45ae44781e313540af"; // deployed Vercel branch @ audit
const SHARED_WITNESS_ACCOUNT = process.env.WITNESS_EXPECTED_ACCOUNT || "acct_01KX3TQ8Z0ME1455RW16JC4ENQ";

/** Identity the card is anchored to. Supplied by stayIdentity.ts, which owns the key. */
export interface StayCardIdentity {
  did: string;
  keyId: string;
}

export function buildStayAgentCard(now: string, identity: StayCardIdentity) {
  return {
    protocolVersion: "0.3.0",
    name: "citizenM Stay Agent",
    description:
      "Governs a hotel guest's on-property journey (check-in, in-stay, check-out) at citizenM by proposing actions on Apaleo exceptions and routing the ones beyond its authority to a human. A bespoke build, not yet a normalised VDA deployment: it decides its own authority, runs its own human queue, executes its own writes, and seals under a borrowed identity. Running against the Apaleo SANDBOX only.",
    url: "https://stay-agent-mikerawsonnzs-projects.vercel.app",
    preferredTransport: "JSONRPC",
    version: "0.1.0-identity",
    gitSha: GIT_SHA,

    // Stay Agent's own DID. Resolves to /.well-known/did.json on the host in `url`.
    did: identity.did,

    provider: { organization: "citizenM Hotels", url: "https://citizenm.com" },

    capabilities: { streaming: false, pushNotifications: false, stateTransitionHistory: true },
    defaultInputModes: ["application/json", "text/plain"],
    defaultOutputModes: ["application/json"],

    skills: cardSkills(),

    // Exactly what Stay touches in Apaleo, read vs write. Sandbox only today.
    apaleoScopes: {
      environment: "sandbox",
      read: [
        "GET /booking/v1/reservations/{id} — the reservation a decision is about",
        "GET /finance/v1/folios/{id} and /finance/v1/folios?reservationIds=… — folio status, balance, line items, disputes",
        "GET /inventory/v1/properties — property roster",
      ],
      write: [
        "CheckIn — reservation check-in",
        "CheckOut — reservation check-out",
        "CreateFolioCharge — post a charge to a folio (moves real money in production; sandbox only today)",
        "AmendReservation — shorten/modify a reservation (e.g. release nights on early check-out)",
      ],
      note: "Writes execute INLINE on a governed PASS (lib/stayExecutor.ts) — this agent both decides and writes. Full reservation/folio objects (guest PII included) are read and reach the LLM prompt unminimised; see the no_pii_minimisation_despite_claim caveat.",
    },

    // What Stay Agent genuinely delegates. This list is SHORT on purpose — today Stay owns
    // almost everything the framework would own for it, and that shortness is the finding.
    doesNotOwn: [
      {
        concern: "the tamper-evident ledger and external anchoring",
        owner: "VDA Witness",
        note: "Stay seals TO Witness; it does not run the hash chain, custodial sealing, or the hourly Rekor/TSA anchoring. But it seals under a shared account, not one it owns — see the no_own_identity caveat.",
      },
      {
        concern: "the EU AI Act article/risk logic",
        owner: "C2MD",
        note: "The Article-by-Article assessment is generated by C2MD via the Witness suite key; Stay orchestrates and renders it. The Article 12 record-keeping report is generated by Witness from the trail.",
      },
    ],

    // The honest gaps. Each is something the framework now does generically that Stay still
    // does bespoke, or a claim its surface makes that its implementation does not support.
    caveats: [
      {
        id: "decides_own_authority_hardcoded_bands",
        statement: "Stay computes its own escalation authority in code, against a hardcoded band ladder — not a signed ACP bundle evaluated by ACP's SDK.",
        detail: "The ladder ambassador -> mod -> compliance_officer is a code constant (routes/stay.ts NEXT_BAND); the decision engine calls its ceiling rules against those literal band names (stayDecisionEngine.ts). Authority here is self-asserted, not framework-enforced. This is the single biggest divergence from the governance model.",
      },
      {
        id: "runs_own_hitl",
        statement: "Stay hosts its own human-in-the-loop queue instead of raising items to hitl.getvda.ai.",
        detail: "/stay/hitl/* (pending + respond) is a second implementation of the concept the live HITL service already provides. The two would need to converge for Stay to be a deployment on the substrate rather than a fork of it.",
      },
      {
        id: "executes_domain_writes_inline",
        statement: "Stay both decides AND executes the Apaleo write on a governed PASS.",
        detail: "CheckIn / CheckOut / CreateFolioCharge / AmendReservation are performed inline by the decision path (lib/stayExecutor.ts). The framework model is record-then-the-deployment-executes; Stay fuses the two.",
      },
      {
        id: "no_own_witness_account",
        statement:
          "Stay now controls its own card key (" + identity.keyId + "), but still has no Witness account and no record-signing key. Its decisions seal under a borrowed identity.",
        detail:
          "The did:web genesis closed exactly one gap: an enforcer can now verify that THIS agent published THIS card, and can challenge it to prove control of its DID. It closed none of the seal-custody gap. Stay still runs inside vda-api and seals to the shared Witness account " + SHARED_WITNESS_ACCOUNT + "; a legacy path (lib/vdaWitness.ts) still falls back to a personal email (mikerawsonnz@gmail.com) when WITNESS_KEY_EMAIL is unset. So an enforcer verifying a sealed decision sees the shared account, not Stay Agent — it cannot prove THIS agent sealed it. Do not read a signed card as signed evidence. Provisioning an own Witness account and record-signing key is the next step, and it is a separate key from this one.",
      },
      {
        id: "identity_key_is_process_held",
        statement: "The card key lives in the deployment's environment, not in an HSM or a KMS.",
        detail:
          "STAY_DID_PRIVATE_KEY_B64 is read into process memory at boot. Anyone with deploy access to the Vercel project can read it and sign as Stay Agent. That is an acceptable posture for a sandbox demo and is NOT an acceptable posture for an agent carrying real guests or real money; it would need a KMS-backed signer first.",
      },
      {
        id: "actor_asserted_and_endpoints_unauthenticated",
        statement: "Human resolutions record who the caller SAYS decided; the human is not authenticated and the endpoints have no auth.",
        detail: "resolve_decision writes decided_by from the request body (defaulting to 'Dashboard User'); there is no auth middleware on the Stay routes. Anyone who can reach the service can resolve a governance decision under a name of their choosing.",
      },
      {
        id: "no_pii_minimisation_despite_claim",
        statement: "Stay fetches whole Apaleo reservation/folio objects — including guest PII — and serialises them into the LLM prompt and the human-queue payload. No PII-minimisation layer exists, despite the GDPR report asserting one.",
        detail: "fetchApaleoSnapshot returns full objects; they reach a third-party LLM verbatim and the HITL payload. Only the Witness SEAL is PII-safe (hash + descriptor). The GDPR report's Article 25 'Presidio scrubbing' claim is not backed by code (see the vda-api findings). Mitigated only by sandbox data.",
      },
    ],

    custody: {
      // Two keys matter for this agent. It now holds the first and still lacks the second.
      model: "own-card-key / custodial-seals-under-borrowed-account",
      cardSigningKey: identity.keyId,
      recordSigningKey: null,
      statement:
        "Stay Agent controls the key that signs this card and answers DID-auth challenges, so its IDENTITY is now verifiable: resolve " + identity.did + ", take #key-1, check agentCardSignature. Its EVIDENCE is not. Decisions are still sealed under vda-api's shared Witness identity, not a key Stay controls, so an enforcer can see that Witness recorded a decision under the shared account and cannot prove Stay Agent specifically sealed it. The suite standard is customer-managed with an own record-signing key; Stay meets it for the card and not for the seal.",
      issuerVerification:
        "card: verifiable via " + identity.keyId + ". Seals: none — sealed records carry the shared account, not this DID.",
    },

    // A self-report of the real state — NOT a live-probe of a genuine, admitted service.
    status: {
      checkedAt: now,
      environment: "apaleo_sandbox",
      production: false,
      carries_real_guests: false,
      carries_real_money: false,
      admitted: false,
      admission_note:
        "No Onboarding credential yet. This card is the admission entry ticket and it is now DID-anchored and signed, so it can be presented as one — being signed is not being admitted.",
      identity:
        "own did:web for the card (" + identity.did + "); seals still ride shared account " + SHARED_WITNESS_ACCOUNT,
      note: "These are honest self-declared facts about a pre-deployment demo, not the output of live readiness probes against an admitted service.",
    },

    // Contracts Stay actually honours today. It does NOT yet implement suite auth-via-whoami.
    contracts: [
      {
        id: "holder_binding_responder",
        role: "holder",
        statement:
          "Stay Agent answers a DID-auth challenge at POST /.well-known/did-auth, signing a caller-supplied nonce with " + identity.keyId + ". This is the holder side of Contract B: an enforcer holding a credential that NAMES this subject_did can now bind the presenter to it instead of assuming.",
      },
    ],

    witnessAccountId: SHARED_WITNESS_ACCOUNT, // borrowed, not owned — see custody + no_own_witness_account

    // agentCardSignature is attached by stayIdentity.signStayAgentCard() over the canonical
    // bytes of this object with that key removed. Absent here on purpose: the builder is
    // pure data, the key lives one layer up.
  };
}
